[project]
name = "strava-history-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fitparse>=1.2.0",
    "ipython>=9.9.0",
    "jupyter>=1.1.1",
    "polars>=1.36.1",
    "stravalib>=2.4",
]
